name: mno_lcp
description: This package provide Flutter LCP implementation.
version: 0.1.0
homepage: https://github.com/Mantano/mno_commons_dart
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fimber: ^0.6.1
  universal_io: ^2.0.4
  multiple_localization: ^0.2.2
  ffi: ^1.1.2
  sqflite: ^2.0.0+4
  tuple: ^2.0.0
  uuid: ^3.0.5
  device_info: ^2.0.2
  shared_preferences: ^2.0.8
  flutter_archive: ^4.0.1
  crypto: ^3.0.1
  either_option: ^2.0.0
  hex: ^0.2.0
  mno_fsm: ^0.1.1
  dfunc: ^0.7.2
  dartx: ^0.7.1
  path_provider: ^2.0.5
  url_launcher: ^6.0.12
  collection: ^1.15.0
  mno_shared:
    path: ../mno_shared_dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.mantano.bookari.r2.mno_lcp_dart
        pluginClass: MnoLcpDartPlugin
      ios:
        pluginClass: MnoLcpDartPlugin

  assets:
    - assets/

