name: r2_server_dart
description: Contains the server functions to serve resources in the webview.
version: 0.1.0
homepage: https://github.com/Mantano/r2_server_dart
publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  fimber: ^0.6.1
  pedantic: ^1.11.1
  rxdart: ^0.27.1
  universal_io: ^2.0.4
  r2_commons_dart:
    path: ../r2_commons_dart
  r2_shared_dart:
    path: ../r2_shared_dart

dev_dependencies:
  lints: ^1.0.1
