name: mno_streamer_dart
version: 0.1.0
description: Streamer API and multiple file parsers (PDF, CBZ, Epub) for Dart.
homepage: https://github.com/Mantano/mno_streamer_dart
publish_to: none # Temporary

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bitmap: ^0.1.2
  dfunc: ^0.7.2
  fimber: ^0.6.1
  path: ^1.8.0
  universal_io: ^2.0.4
  xml: ^5.2.0
  mno_commons_dart:
    path: ../mno_commons_dart
  mno_shared_dart:
    path: ../mno_shared_dart

dev_dependencies:
  lints: ^1.0.1
